version: "3.9"

services:
  api:
    build: .
    container_name: blogintern_api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=BlogDb;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
      ConnectionStrings__AdventureWorks: "Server=mssql;Database=AdventureWorksDW2019;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - blog-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: blogintern_mssql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"        # sadece bunu değiştirdik
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

networks:
  blog-network:

volumes:
  mssql_data:
